[[entry]]
played_at = "2026-10-01T21:27:42Z"
path = "http://stream.zeno.fm/g95zm67prfhvv"
title = "Hits Of Lata Mangeshkar [128k] · India"

[[entry]]
played_at = "2026-10-01T21:27:17Z"
path = "http://192.99.8.192:5032/;stream"
title = "Fnf.Fm Hindi [64k] · India"

[[entry]]
played_at = "2026-10-01T21:27:11Z"
path = "https://eu8.fastcast4u.com/proxy/clyedupq/stream"
title = "Radio Mirchi Hindi [128k] · India"

[[entry]]
played_at = "2026-10-01T21:24:14Z"
path = "https://arn-instore.streamguys1.com/wwr_007"
title = "Woolworths Radio"

[[entry]]
played_at = "2026-10-01T03:32:13Z"
path = "http://radio.cliamp.stream/lofi/stream"
title = "Lofi Stream"

[[entry]]
played_at = "2026-09-30T00:22:08Z"
path = "http://harmanradio.net:8000/main_48.mp3"
title = "Harman Radio Australia [48k] · Australia"

[[entry]]
played_at = "2026-09-30T00:21:21Z"
path = "http://abc.streamguys1.com/live/newsradio/icecast.audio"
title = "ABC NewsRadio MP3 [56k] · Australia"

[[entry]]
played_at = "2026-09-30T00:21:13Z"
path = "https://azuracast.vibesounds.in:8010/radio.mp3"
title = "Hindi Gold Radio [128k] · India"

[[entry]]
played_at = "2026-09-30T00:20:25Z"
path = "http://stream.zeno.fm/0zkr7x8ztm0uv"
title = "Hits Of Mohammed Rafi [128k] · India"

[[entry]]
played_at = "2026-09-30T00:20:05Z"
path = "https://stream.zeno.fm/n2fd0edh9k8uv"
title = "Goldy Evergreen [128k] · India"

[[entry]]
played_at = "2026-09-30T00:20:02Z"
path = "http://stream.zeno.fm/84h97t3ewg0uv"
title = "MY RADIO DJ [48k] · India"

[[entry]]
played_at = "2026-09-30T00:19:49Z"
path = "http://millenniumhits.out.airtime.pro:8000/millenniumhits_a"
title = "2B! Radio Sangam Krishna [48k] · India"

[[entry]]
played_at = "2026-09-30T00:19:39Z"
path = "https://stream.zeno.fm/6n6ewddtad0uv"
title = "Bollywood Gaane Purane [128k] · India"
